on:
  push:
  schedule:
    - cron:  '0 6 * * 1'
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.2', '9.4', '9.6']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Build Package
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build
