on:
  push:
    branches:
      - master
      - devel
  schedule:
    - cron:  '0 6 * * 1'
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.4', '9.6', '9.8', '9.10', '9.12']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Build Package
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build
